### ISSUE TITLE
Bug: 회원 조회시 로그인 요청 오류

### ISSUE THREAD

**Issue by tadaHP** [HBNU-SWUNIV/come-capstone23-f12#45]
# Commit Status
 - 알수없음
# When the Bug occurs
- 로그인을 하지 않은 상태에서 회원을 조회한 경우 로그인을 해야한다는 오류 발생 -> 로그인을 하지 않아도 유저 조회는 가능해야함
# Screenshots📸
![image](https://github.com/HBNU-SWUNIV/come-capstone23-f12/assets/46470302/4d436d16-b57d-4050-87c9-cba5c9b73320)

**Comment by jeidiiy** [comment]
로그인하지 않고 특정 유저를 조회하는 상황이 어떤 상황이 있을까요?

**Comment by jeidiiy** [comment]
> 로그인하지 않고 특정 유저를 조회하는 상황이 어떤 상황이 있을까요?

생각해보니 특정 유저의 블로그나 프로필을 조회할 때 필요할 것 같군요

**Comment by tadaHP** [comment]
넵 그런데 로그인되어있지 않으면 조회가 불가능하더라고요. 어느부분에서 로그인체크가 들어가는건지 몰라 issue로 일단 띄워놨습니다
