### ISSUE TITLE
Bug: 로그인 시 한글 데이터 인코딩 오류

### ISSUE THREAD

**Issue by jeidiiy** [HBNU-SWUNIV/come-capstone23-f12#68]
## Commit Status

- #67

## When the Bug occurs

로그인 시 사용자 정보 중 한글 데이터가 인코딩이 깨져서 내려오는 버그가 있습니다.

## Describe the Bug

![image](https://github.com/HBNU-SWUNIV/come-capstone23-f12/assets/57584529/6d9ad767-ce65-4292-8230-9170684977b0)

**Comment by tadaHP** [comment]
회원가입 시에도 문제가 없는것을 확인하였습니다.
SecurityFilter쪽 확인해보겠습니다
