### ISSUE TITLE
Bug: Swagger API Description 이상

### ISSUE THREAD

**Issue by jeidiiy** [HBNU-SWUNIV/come-capstone23-f12#82]
## Commit Status

- #81 

## When the Bug occurs

Swagger API 문서의 설명 오류로 보이는 버그를 발견했습니다. 해당 API는 Comments > POST 인데 회원 정보변경이라는 설명으로 작성되어 있습니다. 수정 바랍니다.

## Describe the Bug

<img width="254" alt="image" src="https://github.com/HBNU-SWUNIV/come-capstone23-f12/assets/57584529/159a1c65-b088-4c7c-9d51-c47e1ca786cc">

**Comment by tadaHP** [comment]
solved at
- #84
