### ISSUE TITLE
Discuss: 댓글 수정 및 삭제 API

### ISSUE THREAD

**Issue by jeidiiy** [HBNU-SWUNIV/come-capstone23-f12#83]
## Commit Status

- #81 

## What is topic

1. 현재 댓글 수정 및 삭제 API 엔드포인트가 /api/posts/{id}/comments 이고 pathvariable인 id를 commentId로 사용합니다. 그러나 이는 REST API의 계층적 구조 규칙에 어긋나게 설계된 API입니다. 올바르게 작성한 예시로는 /api/posts/{postId}/comments/{commentId} 가 될 것으로 판단됩니다.

2. 수정 성공 시 302라는 응답 코드가 내려오고 있는데 이는 SPA 구조에 맞지 않는 응답 형식입니다. 이 경우에는 200(OK)으로 응답하는 것이 바람직해 보입니다.

## Code

- [CommentsApiController - PutMapping](https://github.com/HBNU-SWUNIV/come-capstone23-f12/blob/c192f8604a2b0e3c59d800d0f3328837c072ac39/003%20Code/BE/notion-linked-blog/src/main/java/io/f12/notionlinkedblog/api/comments/CommentsApiController.java#L69C1-L69C1)

**Comment by tadaHP** [comment]
1. 의 경우 api 엔드포인트를 posts/{postsId}/comments/{commentsId}로 하려다 변경하는 과정에서 일어난 것 같습니다.
삭제시 comment의 id 만을 참조할 것이기 때문에 /api/comments/{commentId} 로 변경하고 진행하겠습니다

**Comment by tadaHP** [comment]
2. 의 경우 기존에 리다이렉트로 300번대 코드를 넘기다 200번대로 바꾸는 과정에서 누락되어있던 부분입니다. 수정하겠습니다

**Comment by tadaHP** [comment]
1. 수정은 아래와 같이 진행하겠습니다
![image](https://github.com/HBNU-SWUNIV/come-capstone23-f12/assets/46470302/599a43c0-da6f-4d1f-b798-f9455a4db8f6)

복수, 단수 구분 추가하였습니다

**Comment by tadaHP** [comment]
![image](https://github.com/HBNU-SWUNIV/come-capstone23-f12/assets/46470302/8a6e2cf4-ee10-4cff-98a6-287d9b3e99ee)
RESTful 적용

**Comment by tadaHP** [comment]
solved at
- #84
